### ISSUE TITLE
Some questions on Kernel modules 

### ISSUE THREAD

**Issue by sagittaros** [gytis-ivaskevicius/nixfiles#19]
Hello, I am trying to setup my first NixOS system, and I am a bit stumped at the lines that say:
```
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
```

Some questions I have in my mind (and possibly others') are:
- are these from your `nixos-generate-config` call? If not, how did you discover them and add those to the generated hardware.nix?
- how do we know whether to include the modules in `boot.initrd.` (stage 1) or the `boot.kernelModules`?
- were there any reasons to add them in `availableKernelModules` instead of `kernelModules`. I have a feeling that this is a silly question, you can ignore this question..

Would really appreciate your answer. Thank you

**Comment by gytis-ivaskevicius** [comment]
Hi, 
- These lines are autogenerated by `nixos-generate-config`
- initrd is 'initial ramdisk', generally you only need to add those modules there that are required for booting the system. (filesystems/hardware devices/in case of network booting - networking)
- `availableKernelModules` does not autoload these modules by default whereas `kernelModules` does

For future reference consider asking these questions on Nixos discourse/matrix/discord, more often than not you'll have lower response latency there
